백엔드 프로젝트 세팅
woowa-techcamp-2021/deal-3 pull request #19
Opened 2021-07-14 01:24 UTC by Seogeurim

## 개요 

## 관련 이슈 

closes #9 

## 변경 사항 

 - express 서버 구축
- config, bin, loaders, api/middlewares, api/routes, models, services, utils 로 서버 코드 모듈화
- nodemon 추가
- env-cmd 설정
- typescript 실행 환경 구성

## PR Point 

프로젝트 세팅은 같이 했으므로 마지막 빠진 부분 없는지만 체크 후 바로 머지하면 될 것 같습니다 !

## 참고 사항 

\-

2021-07-14 01:33 UTC, hseoy requested changes

2021-07-14 01:33 UTC, hseoy commented on package.json
> +    "start": "yarn build && tsc -p ./backend && env-cmd node dist/bin/www.js"
`start` 명령의 `tsc -p ./backend`는 `build:be` 명령으로 분리해주고 각 명령마다 fe에 대한 건지, be에 대한 건지 구분해주면 좋을 것 같아요.

2021-07-14 01:34 UTC, Seogeurim commented on package.json
> +    "start": "yarn build && tsc -p ./backend && env-cmd node dist/bin/www.js"
넵 반영하겠습니다 !!

2021-07-14 01:35 UTC, hseoy approved these changes

2021-07-14 01:35 UTC, merged

2021-07-14 02:28 UTC, crongro reviewed
fe/be의  환경설정을 먼저 잘 마치신것 같네요.
수고하셨습니다.

2021-07-14 02:28 UTC, crongro commented on package.json
> +    "start": "yarn build:fe && yarn build:be && env-cmd node dist/bin/www.js"
npm script 를 잘 활용해서 좋네요. 
간단한 빌드 실행은 npm script를 유용하게 사용하면 좋죠.

2021-07-14 08:56 UTC, Seogeurim commented on package.json
> +    "start": "yarn build:fe && yarn build:be && env-cmd node dist/bin/www.js"
우와 감사합니다 !! 😆 😆 😆

2021-07-15 14:54 UTC, hseoy commented on package.json
> +    "start": "yarn build:fe && yarn build:be && env-cmd node dist/bin/www.js"
감사합니다 !!  ㅎㅎㅎ 😆 😆 😆 😆 😆