Navbar 컴포넌트 구현
woowa-techcamp-2021/deal-3 pull request #24
Opened 2021-07-14 15:13 UTC by Seogeurim

## 개요 

Navbar 컴포넌트를 구현합니다. type에 따라 다른 컴포넌트를 만들 수 있도록 합니다.

## 관련 이슈 

closes #13 

## 변경 사항 

- 네브바 기본 레이아웃 구현
- main / white / off-white / invisible type을 props로 받아서 다른 스타일링 적용
- svg 파일에 대한 웹팩 설정
- components, pages 컴포넌트 구조 설정

## PR Point 

실행했을 때 메인 페이지에 4가지 타입의 네브바가 보일 것입니다 ! 잘 나오는지 테스트해주시고 코드 관련해서 개선해야 할 부분 보이면 얼마든지 피드백 주세용 ~

![image](https://user-images.githubusercontent.com/22045163/125646709-989bb0b1-4e2b-454b-9be5-356c0c2933a1.png)

## 참고 사항 

- [React에서 SVG 사용하기(with Webpack)](https://blog.doitreviews.com/development/2020-05-08-react-svg-usage-with-webpack/)
- [webpack - typescript - Importing Other Assets](https://webpack.js.org/guides/typescript/#importing-other-assets)

2021-07-14 16:03 UTC, hseoy requested changes
두 가지 정도 수정 사항을 적었는데 한 가지만 살펴보시면 될 것 같습니다. 

Object 대신에 별도의 타입(PropsType, StateType)을 정의하면 좋겠다라고 리뷰를 남기기는 했지만 해당 부분은 이 이슈에서 다루기보다는 #20 이슈에서 다루는 편이 더 좋겠다라고 생각했기 때문에 당장은 해결하지 않아도 될 것 같아요.

getRightIcon 함수 내에서 사용하는 타입을 enum으로 분리해도 괜찮을 것 같다라고 리뷰 남긴 부분만 살펴보고 의견 남겨주세요.

다른 부분에 경우에는 크게 눈에 띄는 게 없네요. 가장 크게 눈에 띈다고 하면 svg 파일의 내용이 ts 파일 내에 있다는 건데  이건 차차 살펴보기로 하고... svg 파일들 양 많았을 텐데 수정하느라 고생하셨어요 ㅠㅠ....;;;

2021-07-15 01:37 UTC, Seogeurim commented on frontend/src/core/Component.ts
> +class Component<PropsType = Object, StateType = Object> {
말씀 주신대로 extends 문법을 쓰는 편이 더 좋은 것 같습니다 !!
우선 PropsType, StateType 정의를 빈 객체 (`{}`)로 정의해놓고 객체에 어떤 값들을 넣어줄지는 #20 이슈에서 다루면 될 것 같습니다. 반영하여 이렇게 고치도록 하겠습니다 !

2021-07-15 01:55 UTC, Seogeurim commented on frontend/src/components/Navbar/Navbar.ts
> +    return moreVertical;
TypeScript의 enum 관련해서 어떤 상황에서 쓰는 것이 좋을지 찾아보았습니다.

우선 TypeScript 관련 자료가 많이 나오지 않아 Java enum 관련 글, 클린 코드 글도 함께 참고해보았습니다.

클린코드에서는 enum 사용의 중요성을 이야기하고 있습니다. 하지만 상황에 따라 사용하는 것이 좋을 수도, 안 좋을 수도 있겠다는 생각이 들어 찾아보던 중 [Java Enum 활용기](https://techblog.woowahan.com/2527/) 글을 읽게 되었습니다. 자세히 살펴보기 보다는 대략적으로 어떤 상황에서 사용했는지 살펴보았고 **같은 의미를 표현하는 값이 많을 때**, **데이터 그룹을 표현하고 싶을 때**, **추후 변경 가능성을 고려할 때** 사용한다는 느낌이 들었습니다.

[TypeScript enum을 사용하는 이유](https://medium.com/@seungha_kim_IT/typescript-enum%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3b3ccd8e5552) 글에서는 **"같은 ‘종류’를 나타내는 여러 개의 숫자 혹은 문자열을 다뤄야 하는데, 각각 적당한 이름을 붙여서 코드의 가독성을 높이고 싶다면 enum을 사용하세요."** 라고 언급하고 있습니다.

다시 돌아와서 Navbar의 코드를 살펴봤을 때 enum을 사용한다면, enum을 특정 파일에서 관리하고 그것을 import하여 컴포넌트 코드와 컴포넌트를 불러와 사용하는 코드에서 `Type.MAIN` 이런 식으로 코드를 작성해야 합니다. 제 생각에는 Navbar의 type이 정해져 있기 때문에 바뀔 가능성이 없다는 점과 type에 대한 string도 정해져 있다는 점을 고려해봤을 때 enum을 따로 만들고 import하는 방식은 오히려 비효율적이지 않을까 싶습니다. 덧붙여 enum은 여러 컴포넌트에서 공통적으로 사용하고 있으며 같은 종류를 나타내는 여러 개의 값을 다뤄야 할 때 사용하는 것이 더 좋을 것 같습니다.

마지막으로 blueprintjs 라는 타입스크립트로 만들어진 라이브러리의 Button type 이 어떻게 구현되어 있는지 찾아봤습니다.
![image](https://user-images.githubusercontent.com/22045163/125715680-640febba-a0ce-4fe6-89b5-992e7ba66db5.png)
![image](https://user-images.githubusercontent.com/22045163/125715716-efc3decc-d9c8-4a79-82a3-a8e7a83e3cd5.png)
링크 : https://github.com/palantir/blueprint/blob/713d524272713e726fb0eb0e8c88e3f541b22fa1/packages/core/src/components/button/abstractButton.tsx#L90

확인해보시고 피드백 부탁드립니다 ~!!

2021-07-15 02:01 UTC, Seogeurim commented on frontend/src/core/Component.ts
>    }
Component 수정했습니다 ! 확인해주세요 ~!

2021-07-15 02:22 UTC, hseoy commented on frontend/src/components/Navbar/Navbar.ts
> +    return moreVertical;
관련 글도 찾아서 첨부해주셔서 감사합니다. 특정 문법에 대해서 **그냥** 사용하는 것이 아니라 정확한 근거를 제시하는 것은 정말 중요한 것 같습니다. 제가 리뷰 남겼을 때부터 그런 근거를 제시 했었어야 하는 데 하는 아쉬움이 드네요. 정말 감사합니다 :)

2021-07-15 02:23 UTC, hseoy commented on frontend/src/core/Component.ts
>    }
확인했습니다~.

2021-07-15 02:25 UTC, hseoy approved these changes
정말 자세하게 남겨주셔서 놀랐습니다. enum 관련해서 남겨주신 리뷰는 조금만 정리해서 위키에 글로 공유해도 좋을 만큼 좋은 리뷰였습니다. 감사합니다 ㅎㅎ !

2021-07-15 06:25 UTC, Seogeurim commented on frontend/src/components/Navbar/Navbar.ts
> +    return moreVertical;
저도 덕분에 enum에 대해 좀 더 찾아볼 수 있는 기회가 되었네요 !! 좋은 피드백 감사합니당 !! ㅎㅎ

2021-07-15 06:25 UTC, Seogeurim commented
안 그래도 위키에 올리면 좋을 것 같다는 생각입니다 ! 오늘 밤에 한 번 정리해서 올려둘게요 ~! 😆 😆

2021-07-15 06:27 UTC, Seogeurim commented
예상 소요 시간 : 4h
실제 소요 시간 : 3h + PR 리뷰 시간 0.5h

2021-07-15 06:27 UTC, merged