메인 페이지 아이템 목록 구현
woowa-techcamp-2021/deal-3 pull request #46
Opened 2021-07-19 13:33 UTC by hseoy

## 개요 

메인페이지의 아이템 목록을 구현합니다.

## 관련 이슈 

#44 

## 변경 사항 

- Item 컴포넌트 구현
- ItemList 컴포넌트 구현
- 아이템 클릭 이벤트 설정
- MainPage 페이지 컴포넌트 구현
- MainPage 컴포넌트에서 더미 데이터를 사용해 아이템 목록 구현
- SlidingAnimation props 중 disable을 enable로 네이밍 변경

메인인페이지 구현 내용

<img width="384" alt="스크린샷 2021-07-19 오후 10 21 34" src="https://user-images.githubusercontent.com/75124422/126167943-aa0cf4aa-05dd-4cdf-a545-59e9525ed0b5.png">

## PR Point 

- 각 컴포넌트의 마크업/스타일/이벤트 설정에는 오류가 없는지
- 세부적으로 개선사항은 없는지
에 대해서 확인해주세요 ~!

## 참고 사항 

없음

2021-07-19 15:51 UTC, Seogeurim commented
우선 코드를 보기 전, UI에서 개선할 부분이 몇 가지 보입니다.

- 렌더링 시 콘솔에 아이템 정보가 뜨는데 지워야할 것 같습니다.
- 아이템 리스트 클릭할 때 에러가 뜹니다. 해결해야할 것 같습니다.
- 아이템 리스트에 마우스를 올렸을 때 cursor: pointer를 적용해야할 것 같습니다.
- 오른쪽 상단 하트를 눌렀을 때 색깔이 바뀌는 이벤트 정도는 구현이 필요할 것 같습니다.
- 아래를 비교해보시면 오른쪽 하단 아이콘의 수평 레이아웃이 맞지 않는 점, 크기 조정 등이 필요해보입니다.
  ![image](https://user-images.githubusercontent.com/22045163/126188677-99de3ba5-3e9e-4cb1-8212-84f2586136aa.png)
  ![image](https://user-images.githubusercontent.com/22045163/126188694-a34c0592-d62d-43cc-8387-e7d3b41ad487.png)

2021-07-19 15:51 UTC, Seogeurim commented
@hseoy UI 개선 작업이 끝나면 언급 부탁드립니다 ..!! 그 후 코드 리뷰를 진행하겠습니다 !

2021-07-20 00:58 UTC, hseoy commented
@Seogeurim  말씀하신 사항에 대해서는 대부분 개선을 했습니다..!! 그런데 오른쪽 하단 아이콘의 경우 svg가 inline으로 width/height 24px로 설정되어 있어서 크기를 변경할 수 없어 반영을 못했습니다. 이 부분에 대해서는 svg를 그 다른 캠퍼분이 올려주신 font 파일로 변환하는 이슈를 생성해서 해결 후에 해당 이슈에서 이렇게 svg로 사용한 부분을 font로 변환하는 작업/ui 수정 작업을 진행하면 어떨까 싶은데 어떤가요??

2021-07-20 01:03 UTC, Seogeurim commented
font 파일로 변환하는 이슈를 만드는 것은 현실적으로 시간적인 문제를 고려해야할 것 같습니다. 그보다는 css에서 svg 자체에 접근이 가능하도록 구조를 만들어뒀으므로 css로 조정하는 것이 좋을 것 같습니다. https://css-tricks.com/scale-svg/

2021-07-20 01:15 UTC, hseoy commented
> 그런데 오른쪽 하단 아이콘의 경우 svg가 inline으로 width/height 24px로 설정되어 있어서 크기를 변경할 수 없어 반영을 못했습니다.

알고보니까 이게 잘못된 거였네요,, 제가 실수해서 다른 요소에 width/height를 변경해서 확인했던 거였습니다. 반영하도록 하겠습니다. 자료 감사합니다...!!

2021-07-20 01:52 UTC, hseoy commented
@Seogeurim 말씀해주신 리뷰 내용대로 UI 개선 작업을 완료했습니다 !! 오른쪽 하단 아이콘에 대해서 크기를 조절하고 채팅 아이콘과 하트 아이콘 사이에 디자인 시안대로 간격을 추가했습니다!

<img width="383" alt="스크린샷 2021-07-20 오전 10 50 56" src="https://user-images.githubusercontent.com/75124422/126250192-1e6bddcc-cbcd-4b77-aa14-476d9896c4f2.png">

2021-07-20 05:09 UTC, Seogeurim requested changes
메인 페이지 실행해서 확인해보았습니다! 한 가지 개선점을 남기자면, 아이템 리스트에 클릭 아이콘/아이템 핸들러에서 setState를 해주다보니까 리렌더링이 되어서 스크롤이 올라가는데 이 문제를 해결해야할 것 같습니다. 
수고하셨습니다 ~~!!

2021-07-20 05:09 UTC, Seogeurim commented on frontend/src/components/ItemList/ItemList.ts
> +  }
어떤 작업을 해준 것인가요?

2021-07-20 06:56 UTC, hseoy commented on frontend/src/components/Item/Item.ts
> +}
넵, 그런데 인터페이스들을 보면 해당 컴포넌트를 위해서만 사용되는 인터페이스(ex-ButtonRole)가 있고 위처럼 일반적으로 사용될 수 있는 인터페이스들이 있습니다. 이것들을 전부 한 모듈에서 관리를 할 것인지 아니면 공통으로 사용되는 것들만 분리를 할 것 인지에 대해서 결정해야 할 것 같습니다. 관련해서 의견 주세요~.

2021-07-20 06:59 UTC, hseoy commented on frontend/src/utils/date.ts
> +  }
dataBig과 dataSmall에 담겨지는 값이 달라지지 않나요? 기존 코드의 경우 dateBig에는 최근 날짜에 대한 Date객체가, dataSmall에는 이전 날짜에 대한 Date 객체가 담겨있는 반면, 제안해주신 코드의 경우에는 getTime() 메서드를 호출했을 때의 큰 값이 저장되는 것 같습니다.

2021-07-20 07:02 UTC, hseoy commented on frontend/src/utils/date.ts
> +  }
그래서 이후 return을 할 때 `dateBig.getFullYear() - dateSmall.getFullYear()` 등의 연산에서 오류를 발생시킬 것 같은 데 어떤가요?

2021-07-20 07:03 UTC, hseoy commented on frontend/src/pages/MainPage/itemListDummy.ts
> +export default itemListDummy;
넵, 좋습니다!! 여러 폴더에 나누어져 있는 것보다는 모아서 관리를 하는 편이 개발 중 테스트할 때도 좋고 이후 삭제할 때도 좋을 것 같네요.

2021-07-20 07:04 UTC, hseoy commented on frontend/src/_App.ts
> +import { ButtonTestPage, MainPage } from './pages';
넵, 이제 _App.ts 와 같은 테스트용 코드들을 정리하고 앱에 필요한 코드들로 채워나갈 시점이 온 것 같습니다!

2021-07-20 07:23 UTC, hseoy commented on frontend/src/utils/date.ts
> +  return `${timeSince.value}${timeUnits[timeSince.i]} 전`;
`getTimeSince` 함수는 매개변수로 받은 Date 객체와 현재 시간을 기준으로 한 Date 객체를 비교하여 `2초 전`, `2시간 전` 과 같은 문자열을 반환하는 함수입니다. 

이를 위해서 먼저 `diffDate` 함수를 호출하여 비교값을 가져오게 됩니다. 만약 매개 변수로 받은 Date 객체가 담고 있는 시간이 현재 시간으로부터 5분 30초 전이라고 한다면 diffDate 함수의 리턴 값은 아래와 같게 됩니다.

```ts
{
    year: 0,
    month: 0,
    day: 0,
    hour: 0,
    minutes: 5,
    seconds: 30,
}
```

여기서 이러한 비교 값을 사용해서 `2초 전`, `2시간 전`과 같은 문자열을 생성하기 위해서는 가장 상위의 `0이 아닌 단위` 가 무엇인지를 알아야 합니다. 현재 문자열 생성 시 하위의 단위(현재 단위가 `시간`이라 하면 `분`과 `초`는 하위 단위)는 신경쓰지 않고 있고 비교 값이 0인 단위는 의미가 없기 때문에 가장 상위의 단위이면서 `0`이 아닌 단위를 찾아야 합니다.

이를 위해 위의 diffDate의 리턴값에서 value 값만 `Object.values`를 사용해서 추출하였고, 추출된 value 배열에 대해 `map` 메서드를 사용해서 index 정보와 함께 아래와 같은 형태의 배열로 변환하였습니다. 

```ts
[
    { value: 0, i: 0 }, // year
    { value: 0, i: 1 }, // month
    { value: 0, i: 2 }, // day
    { value: 0, i: 3 }, // hour
    { value: 5, i: 4 }, // minutes
    { value: 30, i: 5 }, // seconds
]
```

그리고 위 배열에 대하여 filter를 사용해서 value값이 0인 요소들을 모두 지워줬습니다.

```ts
[
    { value: 5, i: 4 }, // minutes
    { value: 30, i: 5 }, // seconds
]
```

위에서 언급했던 것이 `0이 아닌 가장 상위의 단위`를 찾아야 한다는 것인데, 이렇게 변환한 배열의 첫 번째 요소가 가장 상위의 단위에 대한 정보와 그 값을 저장하고 있다는 것을 확인할 수 있을 것입니다. 즉 `timeSince`에는 `{ value: 5, i: 4 }`가 저장됩니다.

그리고 단위 정보를 index에서 문자열로 변환해주기 위해서 timeUnits라는 상수를 정의해줬고 timeSince의 i 속성을 사용해서 단위 문자열을 가져오게 됩니다.

```ts
const timeUnits = ['년', '달', '일', '시간', '분', '초'];
```

이렇게 가져온 단위와 value를 결합하게 되면 매개변수로 받은 Date객체가 현재 시간으로부터 얼마 전에 만들어졌는 지를 `2초 전`, `2시간 전` 과 같이 확인할 수 있게 됩니다.

여기까지가 `getTimeSince` 함수의 동작이었습니다.

2021-07-20 07:30 UTC, hseoy commented on frontend/src/pages/MainPage/MainPage.ts
> +  }
질문의 의도를 모르겠습니다. 음,,,, isSaler를 토글하도록 설정한 이유를 묻는다고 하면 샘플 코드의 목적으로 작성된 코드입니다. 해당 부분에 대해서는 item id 등을 사용해서 해당 아이템에 대한 상세 페이지로 이동하도록 작성을 하게 될 예정입니다만 현재까지는 아이템 상세 페이지까지 만들어지지는 않았기에 동작을 확인할 수 있는 샘플 코드를 작성해주었습니다.

2021-07-20 07:32 UTC, hseoy commented on frontend/src/components/ItemList/ItemList.ts
> +      </div>
감사합니다!! 저도 reduce나 이런 배열 관련된 메서드들을 잘 사용하면 코드가 많이 간결해지는 모습을 다른 코드들을 보면서 많이 보았기에 의도적으로 많이 사용하려 했습니다. 다만 가독성 등 코드를 이해하는 데 어려움을 줄 수 있을 수도 있기에 그런 점에 대해서는 그림님께서 많이 잡아주셨으면 해요 ㅎㅎ

2021-07-20 07:36 UTC, hseoy commented on frontend/src/components/ItemList/ItemList.ts
> +  }
해당 메서드는 props로 받은 매개변수인 onClickItemHandler와 onClickIconHandler에 대해서 이벤트가 발생했을 때 해당 아이템이 아이템 리스트에서 위치한 index 정보와 아이템 정보를 매개변수로 넘겨주기 위한 이벤트 핸들러를 생성해주는 함수입니다. 

그리고 이렇게 생성된 이벤트 핸들러는 Item 컴포넌트의 onClickItemHandler, onClickIconHandler props로 전달되게 됩니다. 

결과적으로 아이템과 아이템 내 오른쪽 상단 아이콘을 클릭했을 때 대상 아이템의 index와 정보를 이벤트 핸들러의 매개변수에서 받도록 하기 위한 작업을 수행한다고 보시면 됩니다.

2021-07-20 07:38 UTC, Seogeurim commented on frontend/src/components/Item/Item.ts
> +}
공통으로 사용되는 것들만 분리를 하면 될 것 같습니다 !!

2021-07-20 07:41 UTC, Seogeurim commented on frontend/src/utils/date.ts
> +  }
아 제가 코드를 완전 잘못 썼네요 !! ㅋㅋㅋㅋㅋ 이럴수가 
getTime으로 비교해서 date 객체를 넣는건데 getTime을 저장했네요 ㅎㅎ
해당 리뷰는 무시해주세효 ~~~!

2021-07-20 07:41 UTC, hseoy commented on frontend/src/components/Item/Item.ts
> +}
넵! 좋습니다~!

2021-07-20 07:49 UTC, Seogeurim commented on frontend/src/utils/date.ts
> +  return `${timeSince.value}${timeUnits[timeSince.i]} 전`;
와우 이렇게 상세히 적어주시는데 이해를 못할 수가 없었습니다. 완벽히 이해했습니다. 
자칫하면 길어질 수 있는 코드를 매우 간결하게 작성하신 것 같습니다 !! 추후 위키에 정리해도 좋겠네요 ~! 많이 배워갑니다 ❗️

2021-07-20 07:51 UTC, Seogeurim commented on frontend/src/pages/MainPage/MainPage.ts
> +  }
isSaler를 토글하는 것이 샘플 코드의 목적이지만 어색한 부분이 있는 것 같아 질문한 것이었습니다 !!
클릭했을 때 상세페이지로 이동하는 것까지만 작성해보는 것이 어떤가요? ex. history.push('/detail?id=3')

2021-07-20 07:58 UTC, Seogeurim commented on frontend/src/components/ItemList/ItemList.ts
> +  }
혹시 그보다도 item 데이터를 받으면 item의 id 값이 있을텐데, 그 id 값을 data 속성으로 저장하고
item에 클릭 이벤트가 발생하였을 때 그 data 속성의 값을 찾아서 해당 이벤트의 콜백 함수에 전달해주고,
콜백함수에서는 item id 값으로 item을 찾아서 원하는 작업을 수행하도록 하는 것은 어떤가요?

2021-07-20 10:43 UTC, hseoy commented on frontend/src/utils/date.ts
> +  }
넵 ㅋㅋㅋㅋㅋㅋ ㅎㅎㅎ

2021-07-20 10:44 UTC, hseoy commented on frontend/src/pages/MainPage/MainPage.ts
> +  }
넵, 좋습니다!

2021-07-20 10:45 UTC, hseoy commented on frontend/src/components/ItemList/ItemList.ts
> +  }
이벤트 위임을 구현하자는 의미로 들리는 데 맞을까요?? data 속성을 사용하면 이벤트 핸들링 구조가 더 깔끔해지겠네요! 한번 시도해보도록 하겠습니다!

2021-07-21 06:15 UTC, hseoy commented
@Seogeurim 리뷰 내용 반영 했는 데 확인해주세요!

2021-07-21 06:46 UTC, hseoy commented
@Seogeurim  하트 토글이 안된다는 문제 수정했습니다. 확인해주세요~

2021-07-21 07:17 UTC, hseoy commented
@Seogeurim 이번엔 진짜로 하트 토글이 안된다는 문제 해결했습니다. 확인해주세요~

2021-07-21 07:17 UTC, Seogeurim commented
zㅋㅋㅋㅋㅋ네 ~

2021-07-21 07:19 UTC, Seogeurim approved these changes
확인 완료했습니다 !! 👍

2021-07-21 07:19 UTC, merged