카테고리 페이지 구현
woowa-techcamp-2021/deal-3 pull request #49
Opened 2021-07-19 17:11 UTC by hseoy

## 개요 

카테고리 페이지를 구현합니다.

## 관련 이슈 

#47 

## 변경 사항 

- CategoryListItem 컴포넌트 구현
- CategoryList 컴포넌트 구현
- CategoryPage 컴포넌트 구현
- category 정보 constants로 분리
- NavLink를 사용해 링크 이동시 QueryString을 삭제하도록 수정

구현 내용

<img width="300" src="https://user-images.githubusercontent.com/75124422/126199428-a5123792-2a1b-4fb3-bb46-887b126ce4db.gif" alt="구현내용">

## PR Point 

- 각 컴포넌트의 구조가 적절한지
- 각 컴포넌트의 세부 구현에서 개선되어야 할 부분은 없는지
- category 정보를 constants로 분리한 것은 괜찮은지
에 대해서 확인해주세요~!!

## 참고 사항 

없음

2021-07-20 08:02 UTC, Seogeurim commented
_App.ts에 오류가 있고 카테고리 페이지 라우터 연결이 안 되어 있습니다 !!
이제부터 동작 가능한 코드를 올려야 하는데 PR 전 제가 테스트해볼 수 있을지 한 번 확인해주시면 감사합니다 ~!

2021-07-20 10:50 UTC, hseoy commented
메인페이지 이슈에서 _App.ts를 지울 예정이라 #44  해당 이슈를 먼저 닫고 나서 이 이슈 진행하도록 하겠습니다!

2021-07-21 07:57 UTC, hseoy commented
dev와 머지했을 때 로그인 페이지 슬라이딩 애니메이션과 카테고리 페이지 슬라이딩 애니메이션이 동시에 적용되지 않아 새로운 이슈 발행 : #50

2021-07-21 10:27 UTC, hseoy commented
슬라이딩 애니메이션의 경우, 현재 오류가 수정되지 않아 슬라이딩 애니메이션을 적용한 부분은 주석 처리하고 진행하였습니다. #50 에서 추후 작업하도록 하겠습니다.

2021-07-21 10:49 UTC, Seogeurim requested changes
- 카테고리페이지에서 `goMainPageWithCategoryIndex` 함수를 가지고 있고, 그 함수를 카테고리리스트, 카테고리아이템으로 타고타고 내려가 전달해주던데, 그럴 필요 없이 히스토리가 전역에서 접근 가능하므로 카테고리아이템에서 해당 함수를 addEvent만 해주면 될 것 같습니다. (props로 카테고리 아이디값만 받아서)
- 카테고리 아이템 이미지를 지금 추가하는 것이 좋을 것 같습니다. 아이콘 사이트로 제가 많이 이용하는 것은 flaticon입니다!
- 저도 방금 알았는데 카테고리에 '식물', '기타 중고물품'도 있네요 !
- 데이터베이스에서 관리되고 있는 카테고리 아이디가 1번부터 시작하기 때문에 0번 인덱스가 아닌 1번 인덱스부터 시작하는 것으로 하면 좋을 것 같네요 ! (ex. 디지털기기 id -> 지금은 0번으로 요청되는데(?category=0) 1번부터 요청되게)

2021-07-21 10:49 UTC, Seogeurim commented on frontend/src/App.ts
> +import CategoryPage from './pages/CategoryPage/CategoryPage';
카테고리 페이지 임포트 합쳐주시고 주석 지워야 할 것 같습니당 !

2021-07-21 10:49 UTC, Seogeurim commented on frontend/src/App.ts
> +    // );
주석 지워주세요 ..!

2021-07-21 10:49 UTC, Seogeurim commented on frontend/src/pages/CategoryPage/CategoryPage.ts
> +    );
카테고리 네브바에 타이틀이 설정되지 않은 것 같습니다.

2021-07-21 10:49 UTC, Seogeurim commented on frontend/src/pages/CategoryPage/CategoryPage.ts
> +  });
카테고리인덱스를 ""를 붙이지 않고 그냥 숫자로 붙여주는게 좋을 것 같습니다.

2021-07-21 10:52 UTC, hseoy commented on frontend/src/pages/CategoryPage/CategoryPage.ts
> +  });
넵!

2021-07-21 11:33 UTC, hseoy commented on frontend/src/pages/CategoryPage/CategoryPage.ts
> +  });
넵, 반영하도록 하겠습니다!

2021-07-21 11:34 UTC, hseoy commented on frontend/src/pages/CategoryPage/CategoryPage.ts
> +    );
뭔가 부족하다 생각했었는 데 타이틀이 설정 안되어 있었군요! 감사합니다!!

2021-07-21 11:34 UTC, hseoy commented on frontend/src/App.ts
> +    // );
넵....!

2021-07-21 11:34 UTC, hseoy commented on frontend/src/App.ts
> +import CategoryPage from './pages/CategoryPage/CategoryPage';
알겠습니다...!!

2021-07-21 13:05 UTC, hseoy commented
@Seogeurim 리뷰 남겨주신 내용들에 대해서 모두 반영했습니다! 확인해주세요~~!!

2021-07-21 13:48 UTC, Seogeurim commented
카테고리 화면 너무 귀여워졌네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 
수정 사항 모두 확인했습니다 !! 코드가 전보다 훨씬 깔끔해진 것 같습니다 👍 😆 

한가지 질문이 있습니다 !
![image](https://user-images.githubusercontent.com/22045163/126499457-82a07772-2cfc-48da-9a34-2f488413fafb.png)
여기 코드에서 해당 컴포넌트에서 사용하는 함수를 맨 위로 빼서 상수로 선언하셨던데, 저는 지금까지 필요한 함수를 컴포넌트 안에 작성했습니다. 컨벤션을 맞추면 될 것 같은데 어느쪽으로 맞추는 것이 좋을까요?

2021-07-21 15:58 UTC, hseoy commented
ESLint 설정의 `"class-methods-use-this"` rule에서 class method 내에 this를 사용하지 않으면 error를 발생시키도록 설정해두었었습니다. 그래서 this를 사용하지 않는 메서드의 경우에는 별도의 함수로 분리해서 class 바깥으로 빼주었습니다. 위 코드의 경우에는 this를 사용하지 않았기에 분리를 해준 거라 별도의 컨벤션을 맞출 필요는 없을 것 같아요!

2021-07-21 16:00 UTC, Seogeurim commented
아하 네 이해했습니다 ! 저도 추후 this를 사용하지 않는 경우 위와 같이 분리하면 좋을 것 같네요 !! 😆

2021-07-21 16:00 UTC, Seogeurim approved these changes

2021-07-21 16:00 UTC, merged